/* soapTridentServiceSoapProxy.h
   Generated by gSOAP 2.7.13 from WSHeader.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapTridentServiceSoapProxy_H
#define soapTridentServiceSoapProxy_H
#include "soapH.h"
class TridentServiceSoap
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'TridentServiceSoap' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	TridentServiceSoap()
	{ soap = soap_new(); endpoint = "http://localhost/TridentWebServiceSetup/TridentService.asmx"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://www.w3.org/2003/05/soap-envelope", "http://schemas.xmlsoap.org/soap/envelope/", NULL},
	{"SOAP-ENC", "http://www.w3.org/2003/05/soap-encoding", "http://schemas.xmlsoap.org/soap/encoding/", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "http://microsoft.com/wsdl/types/", NULL, NULL},
	{"c14n", "http://www.w3.org/2001/10/xml-exc-c14n#", NULL, NULL},
	{"wsse", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd", NULL, NULL},
	{"wsu", "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", NULL, NULL},
	{"ds", "http://www.w3.org/2000/09/xmldsig#", NULL, NULL},
	{"wsp", "http://schemas.xmlsoap.org/ws/2004/09/policy", NULL, NULL},
	{"ns4", "http://tempuri.org/TridentServiceSoap", NULL, NULL},
	{"ns1", "http://tempuri.org/", NULL, NULL},
	{"ns5", "http://tempuri.org/TridentServiceSoap12", NULL, NULL},
	{"ns6", "http://schemas.microsoft.com/research/datalayer/2010/03/SimpleProxy/SimpleProxySoap", NULL, NULL},
	{"ns3", "http://schemas.microsoft.com/research/datalayer/2010/03/SimpleProxy", NULL, NULL},
	{"ns7", "http://schemas.microsoft.com/research/datalayer/2010/03/SimpleProxy/SimpleProxySoap12", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~TridentServiceSoap() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'Authenticate' of service 'TridentServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns4__Authenticate(_ns1__Authenticate *ns1__Authenticate, _ns1__AuthenticateResponse *ns1__AuthenticateResponse) { return soap ? soap_call___ns4__Authenticate(soap, endpoint, NULL, ns1__Authenticate, ns1__AuthenticateResponse) : SOAP_EOM; };
	/// Invoke 'TerminateJob' of service 'TridentServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns4__TerminateJob(_ns1__TerminateJob *ns1__TerminateJob, _ns1__TerminateJobResponse *ns1__TerminateJobResponse) { return soap ? soap_call___ns4__TerminateJob(soap, endpoint, NULL, ns1__TerminateJob, ns1__TerminateJobResponse) : SOAP_EOM; };
	/// Invoke 'GetMachineList' of service 'TridentServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns4__GetMachineList(_ns1__GetMachineList *ns1__GetMachineList, _ns1__GetMachineListResponse *ns1__GetMachineListResponse) { return soap ? soap_call___ns4__GetMachineList(soap, endpoint, NULL, ns1__GetMachineList, ns1__GetMachineListResponse) : SOAP_EOM; };
	/// Invoke 'GetJobList' of service 'TridentServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns4__GetJobList(_ns1__GetJobList *ns1__GetJobList, _ns1__GetJobListResponse *ns1__GetJobListResponse) { return soap ? soap_call___ns4__GetJobList(soap, endpoint, NULL, ns1__GetJobList, ns1__GetJobListResponse) : SOAP_EOM; };
	/// Invoke 'GetJobStatus' of service 'TridentServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns4__GetJobStatus(_ns1__GetJobStatus *ns1__GetJobStatus, _ns1__GetJobStatusResponse *ns1__GetJobStatusResponse) { return soap ? soap_call___ns4__GetJobStatus(soap, endpoint, NULL, ns1__GetJobStatus, ns1__GetJobStatusResponse) : SOAP_EOM; };
	/// Invoke 'GetWorkflowList' of service 'TridentServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns4__GetWorkflowList(_ns1__GetWorkflowList *ns1__GetWorkflowList, _ns1__GetWorkflowListResponse *ns1__GetWorkflowListResponse) { return soap ? soap_call___ns4__GetWorkflowList(soap, endpoint, NULL, ns1__GetWorkflowList, ns1__GetWorkflowListResponse) : SOAP_EOM; };
	/// Invoke 'RunWorkflow' of service 'TridentServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns4__RunWorkflow(_ns1__RunWorkflow *ns1__RunWorkflow, _ns1__RunWorkflowResponse *ns1__RunWorkflowResponse) { return soap ? soap_call___ns4__RunWorkflow(soap, endpoint, NULL, ns1__RunWorkflow, ns1__RunWorkflowResponse) : SOAP_EOM; };
	/// Invoke 'GetWorkflowOuputList' of service 'TridentServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns4__GetWorkflowOuputList(_ns1__GetWorkflowOuputList *ns1__GetWorkflowOuputList, _ns1__GetWorkflowOuputListResponse *ns1__GetWorkflowOuputListResponse) { return soap ? soap_call___ns4__GetWorkflowOuputList(soap, endpoint, NULL, ns1__GetWorkflowOuputList, ns1__GetWorkflowOuputListResponse) : SOAP_EOM; };
	/// Invoke 'GetDataProductList' of service 'TridentServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns4__GetDataProductList(_ns1__GetDataProductList *ns1__GetDataProductList, _ns1__GetDataProductListResponse *ns1__GetDataProductListResponse) { return soap ? soap_call___ns4__GetDataProductList(soap, endpoint, NULL, ns1__GetDataProductList, ns1__GetDataProductListResponse) : SOAP_EOM; };
	/// Invoke 'GetDataProduct' of service 'TridentServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns4__GetDataProduct(_ns1__GetDataProduct *ns1__GetDataProduct, _ns1__GetDataProductResponse *ns1__GetDataProductResponse) { return soap ? soap_call___ns4__GetDataProduct(soap, endpoint, NULL, ns1__GetDataProduct, ns1__GetDataProductResponse) : SOAP_EOM; };
};
#endif
